### ISSUE TITLE
Holidays not appearing in calendar or usable for Garbage Collection

### ISSUE THREAD

**Issue by lichenophile** [bruxy70/Holidays#31] opened 2022-04-06 21:51 UTC
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

![image](https://user-images.githubusercontent.com/67679349/162069705-f51ffa58-954b-40bd-94b6-bf1a4eb06b66.png)
I have installed and am receiving correct data from the entity. 
However the calendar does not show the holidays reflected in the entity state, nor can I use a blueprint to shift dates for garbage collection:
![image](https://user-images.githubusercontent.com/67679349/162070063-55167e2c-b8e7-4aa3-b83b-d2d744852c01.png)

### Configuration

```JSON
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.4.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Australia/Melbourne",
    "os_name": "Linux",
    "os_version": "5.10.108",
    "supervisor": "2022.03.5",
    "host_os": "Home Assistant OS 7.6",
    "docker_version": "20.10.9",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "spotcast": {
      "version": "v3.6.27",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    },
    "garbage_collection": {
      "version": "4.6",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "qbittorrent_alternative_speed": {
      "version": "1.3.2",
      "requirements": [
        "qbittorrent-api==0.4.2"
      ]
    },
    "breaking_changes": {
      "version": "21.12.0",
      "requirements": [
        "pyhaversion>=21.3.0",
        "integrationhelper>=0.2.2",
        "awesomeversion"
      ]
    },
    "bureau_of_meteorology": {
      "version": "1.1.1",
      "requirements": []
    },
    "xiaomi_gateway3": {
      "version": "2.0.9",
      "requirements": [
        "zigpy>=0.33.0"
      ]
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "entity_controller": {
      "version": "9.2.10",
      "requirements": [
        "transitions==0.8.8"
      ]
    },
    "xiaomi_miot": {
      "version": "0.5.5",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "jellyfin": {
      "version": "1.0.10",
      "requirements": [
        "jellyfin-apiclient-python==1.7.2"
      ]
    },
    "circadian_lighting": {
      "version": "2.0.6",
      "requirements": []
    },
    "google_geocode": {
      "version": "0.1.9",
      "requirements": []
    },
    "illuminance": {
      "version": "2.4.0",
      "requirements": []
    },
    "start_time": {
      "version": "1.1.6",
      "requirements": []
    },
    "sun2": {
      "version": "2.0.3",
      "requirements": []
    },
    "hass_agent_notifier": {
      "version": "2022.3.15",
      "requirements": []
    },
    "average": {
      "version": "2.2.1",
      "requirements": []
    },
    "thermal_comfort": {
      "version": "1.4.3",
      "requirements": []
    },
    "browser_mod": {
      "version": "1.3.1",
      "requirements": []
    },
    "cupertino": {
      "version": "3.0.2",
      "requirements": []
    },
    "holidays": {
      "version": "1.7.1",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.13"
      ]
    },
    "hacs": {
      "version": "1.24.3",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "public_transport_victoria": {
      "version": "0.3.2",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "holidays",
    "name": "Holidays",
    "version": "1.7.1",
    "documentation": "https://github.com/bruxy70/Holidays/",
    "issue_tracker": "https://github.com/bruxy70/Holidays/issues",
    "iot_class": "calculated",
    "dependencies": [],
    "config_flow": true,
    "codeowners": [
      "@bruxy70"
    ],
    "requirements": [
      "python-dateutil>=2.8.2",
      "holidays>=0.13"
    ],
    "is_built_in": false
  },
  "data": {
    "entity_id": "calendar.holidays",
    "state": 8,
    "attributes": {
      "next_date": "2022-04-15T00:00:00+10:00",
      "next_holiday": "Good Friday",
      "last_updated": "2022-04-07T07:19:56.488677+10:00",
      "holidays": {
        "2021-01-01": "New Year's Day",
        "2021-01-26": "Australia Day",
        "2021-03-08": "Labour Day",
        "2021-04-02": "Good Friday",
        "2021-04-03": "Easter Saturday",
        "2021-04-04": "Easter Sunday",
        "2021-04-05": "Easter Monday",
        "2021-04-25": "Anzac Day",
        "2021-06-14": "Queen's Birthday",
        "2021-09-24": "Grand Final Day",
        "2021-11-02": "Melbourne Cup",
        "2021-12-25": "Christmas Day",
        "2021-12-26": "Boxing Day",
        "2021-12-27": "Christmas Day (Observed)",
        "2021-12-28": "Boxing Day (Observed)",
        "2022-01-01": "New Year's Day",
        "2022-01-03": "New Year's Day (Observed)",
        "2022-01-26": "Australia Day",
        "2022-03-14": "Labour Day",
        "2022-04-15": "Good Friday",
        "2022-04-16": "Easter Saturday",
        "2022-04-17": "Easter Sunday",
        "2022-04-18": "Easter Monday",
        "2022-04-25": "Anzac Day",
        "2022-06-13": "Queen's Birthday",
        "2022-09-30": "Grand Final Day",
        "2022-11-01": "Melbourne Cup",
        "2022-12-25": "Christmas Day",
        "2022-12-26": "Boxing Day",
        "2022-12-27": "Christmas Day (Observed)",
        "2023-01-01": "New Year's Day",
        "2023-01-02": "New Year's Day (Observed)",
        "2023-01-26": "Australia Day",
        "2023-03-13": "Labour Day",
        "2023-04-07": "Good Friday",
        "2023-04-08": "Easter Saturday",
        "2023-04-09": "Easter Sunday",
        "2023-04-10": "Easter Monday",
        "2023-04-25": "Anzac Day",
        "2023-06-12": "Queen's Birthday",
        "2023-09-29": "Grand Final Day",
        "2023-11-07": "Melbourne Cup",
        "2023-12-25": "Christmas Day",
        "2023-12-26": "Boxing Day"
      }
    },
    "config_entry": {
      "entry_id": "5efcd0e86899ce9f123e2a54bbd213f9",
      "version": 2,
      "domain": "holidays",
      "title": "Holidays",
      "data": {
        "unique_id": "8d1f3a9d-a32d-41a0-8dea-f895f52d2728",
        "icon_normal": "mdi:calendar-blank",
        "country": "AU",
        "observed": true,
        "subdiv": "VIC"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    }
  }
}
```

### Debug logs

```shell
2022-04-07 07:32:15 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated xxxx::xxx:xxxx:xxxx:xxxx for /api/calendars/calendar.holidays using bearer token
2022-04-07 07:32:15 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/calendars/calendar.holidays to xxxx::xxx:xxxx:xxxx:xxxx (auth: True)
2022-04-07 07:32:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 208, in get
assert isinstance(entity, CalendarEventDevice)
AssertionError
2022-04-07 07:32:15 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: name=aiohttp.server, message=['Error handling request'], level=ERROR, source=['components/calendar/__init__.py', 208], timestamp=1649280735.3064353, exception=Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 208, in get
assert isinstance(entity, CalendarEventDevice)
AssertionError
, count=1, first_occurred=1649280735.3064353>
2022-04-07 07:32:15 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140472911361792] Sending {"id":161,"type":"event","event":{"event_type":"system_log_event","data":{"name":"aiohttp.server","message":["Error handling request"],"level":"ERROR","source":["components/calendar/__init__.py",208],"timestamp":1649280735.3064353,"exception":"Traceback (most recent call last):\n File \"/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py\", line 435, in _handle_request\n resp = await request_handler(request)\n File \"/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py\", line 504, in _handle\n resp = await handler(request)\n File \"/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py\", line 117, in impl\n return await handler(request)\n File \"/usr/src/homeassistant/homeassistant/components/http/security_filter.py\", line 60, in security_filter_middleware\n return await handler(request)\n File \"/usr/src/homeassistant/homeassistant/components/http/forwarded.py\", line 100, in forwarded_middleware\n return await handler(request)\n File \"/usr/src/homeassistant/homeassistant/components/http/request_context.py\", line 28, in request_context_middleware\n return await handler(request)\n File \"/usr/src/homeassistant/homeassistant/components/http/ban.py\", line 79, in ban_middleware\n return await handler(request)\n File \"/usr/src/homeassistant/homeassistant/components/http/auth.py\", line 219, in auth_middleware\n return await handler(request)\n File \"/usr/src/homeassistant/homeassistant/components/http/view.py\", line 137, in handle\n result = await result\n File \"/usr/src/homeassistant/homeassistant/components/calendar/__init__.py\", line 208, in get\n assert isinstance(entity, CalendarEventDevice)\nAssertionError\n","count":1,"first_occurred":1649280735.3064353},"origin":"LOCAL","time_fired":"2022-04-06T21:32:15.310414+00:00","context":{"id":"25fb3d382311d886c202e774fcc17df1","parent_id":null,"user_id":null}}}
```

**Comment by drakhart** [comment] 2022-04-07 23:47
I'm having the exact same issue since I updated to HA 2022.4.0, and my logs look the same.

Possibly related to this HA issue: https://github.com/home-assistant/core/issues/69605

**Comment by bruxy70** [comment] 2022-04-08 05:59
Thanks, I confirm the issue. Will find the cause and fix it.

**Comment by bruxy70** [comment] 2022-04-08 17:18
Shoudl be fixed in the new release

**Closed as completed by bruxy70** 2022-04-08 17:18 UTC
Labels: bug

**Comment by drakhart** [comment] 2022-04-08 17:48
It's working on my side after upgrading. Thanks a lot!
